# Generated by Django 3.2.3 on 2021-05-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
