# Generated by Django 3.2.3 on 2021-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0002_attempt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
