# Generated by Django 3.2.3 on 2021-05-29 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0003_alter_attempt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ans_id',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 23, 45, 18, 798354)),
        ),
    ]
