# Generated by Django 3.2.3 on 2021-05-29 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0004_auto_20210529_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='test',
            name='hash',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 0, 39, 7, 362762)),
        ),
    ]
