# Generated by Django 3.2.3 on 2021-05-30 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0006_auto_20210530_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullreport',
            name='score',
        ),
        migrations.AddField(
            model_name='fullreport',
            name='answer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testing_system_app.answer'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 12, 39, 59, 859891)),
        ),
    ]
