# Generated by Django 3.2 on 2021-05-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0007_auto_20210530_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 12, 4, 7, 703398)),
        ),
    ]
