# Generated by Django 3.2 on 2021-05-30 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0008_alter_attempt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='general_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 13, 46, 23, 257038)),
        ),
    ]
