# Generated by Django 3.2.4 on 2021-06-03 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0009_auto_20210530_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalreport',
            name='test_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testing_system_app.test'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 12, 52, 14, 859610)),
        ),
    ]
