# Generated by Django 3.2.4 on 2021-06-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0011_auto_20210606_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 22, 47, 260805)),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 22, 47, 262805)),
        ),
    ]
