# Generated by Django 3.2.4 on 2021-06-08 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing_system_app', '0012_auto_20210608_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 46, 9, 181735)),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 46, 9, 183759)),
        ),
    ]
