# Generated by Django 3.2.4 on 2021-06-08 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system_app', '0013_auto_20210608_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 17, 10, 52, 748401)),
        ),
        migrations.AlterField(
            model_name='generalreport',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 17, 10, 52, 748401)),
        ),
        migrations.CreateModel(
            name='UsersTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system_app.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system_app.student')),
            ],
        ),
    ]
